<a href="https://colab.research.google.com/github/LydiaShammi/MyPythonfile/blob/main/Practice_File_Array_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([2,5,8,11,14,17,20], dtype='U')
arr

array(['2', '5', '8', '11', '14', '17', '20'], dtype='<U2')

In [ ]:
arr=np.array([2,5,8,11,14,17,20], dtype='str')
arr

array(['2', '5', '8', '11', '14', '17', '20'], dtype='<U2')

In [ ]:
arr=np.array([2,5,8,11,14,17])
ar=arr.reshape((2,3))
print(ar)
ar.ndim

[[ 2  5  8]
 [11 14 17]]


2

In [ ]:
a1=np.array([10,20,30])
a= a1.reshape(3,1)
print(a)
b1=np.array([5,6,7])
b= b1.reshape(1,3)
print('\n',b)
c=a+b
print('\n',c)
print(c.ndim)
print(c.shape)

[[10]
 [20]
 [30]]

 [[5 6 7]]

 [[15 16 17]
 [25 26 27]
 [35 36 37]]
2
(3, 3)


In [ ]:
a1=np.array([10,20,30]).reshape(3,1)
b1=np.array([5,6,7]).reshape(1,3)
c=a+b
print('\n',c)
print(c.ndim)
print(c.shape)


 [[15 16 17]
 [25 26 27]
 [35 36 37]]
2
(3, 3)


In [ ]:
a=np.random.rand(5,4)
np.array_split(a,2)

[array([[0.58092582, 0.18786265, 0.6663882 , 0.62069134],
        [0.73121863, 0.56146992, 0.84352302, 0.98741259],
        [0.22105884, 0.49448715, 0.74374512, 0.71746702]]),
 array([[0.44451504, 0.12671845, 0.70814357, 0.27466895],
        [0.55564024, 0.44323264, 0.17009611, 0.62334985]])]

In [ ]:
a=np.random.rand(5,4)
np.hsplit(a,2)


[array([[0.70423855, 0.98292259],
        [0.59853117, 0.92186855],
        [0.49030224, 0.17792119],
        [0.03145246, 0.99512681],
        [0.5464484 , 0.27909814]]), array([[7.68397976e-01, 8.86621998e-01],
        [6.59560631e-01, 7.01416829e-01],
        [5.55346532e-01, 1.23243360e-01],
        [6.63059679e-01, 9.30799653e-01],
        [6.37677878e-05, 3.08611674e-01]])]

In [ ]:
a1=np.array([[6,5,4],
            [3,2,1]])
b1=np.random.randint(1,10,(2,3))
print(a1)
print(b1)
np.vstack((a1,b1))

[[6 5 4]
 [3 2 1]]
[[1 7 4]
 [6 1 9]]


array([[6, 5, 4],
       [3, 2, 1],
       [1, 7, 4],
       [6, 1, 9]])

In [ ]:
a1=np.array([[6,5,4],
            [3,2,1]])
b1=np.random.randint(1,10,(2,3))
print(a1)
print(b1)
arr=np.concatenate((a1,b1))
print(arr)
s=arr.flatten()
print(s)

[[6 5 4]
 [3 2 1]]
[[8 8 1]
 [7 6 5]]
[[6 5 4]
 [3 2 1]
 [8 8 1]
 [7 6 5]]
[6 5 4 3 2 1 8 8 1 7 6 5]


In [ ]:
arr=np.random.randint(1,100,(5,10))
print(arr,'\n')
print(arr.max(axis=1))
print('\n')
print(arr.sum(axis=0))
print('\n')
print(arr.mean())

[[22 37 84 94 13 58 85 48  2 14]
 [29  6 93 39  2  1 76 39 24 71]
 [16 23 93 56 12 97 73 71 79 26]
 [84  7 48 95  4 27 44 58 37 75]
 [23 98 92 77  2 54 57 86 47 37]] 

[94 93 97 95 98]


[174 171 410 361  33 237 335 302 189 223]


48.7


In [ ]:
import pandas as pd
arr=np.random.randint(0,9,10)
print(arr)
ser=pd.Series(arr,index=['i','ii','iii','iv','v']*2)
print(ser)


[8 8 7 1 0 1 8 2 6 3]
i      8
ii     8
iii    7
iv     1
v      0
i      1
ii     8
iii    2
iv     6
v      3
dtype: int64
